name: traffix
description: A old Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.0
  font_awesome_flutter: ^10.1.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  google_sign_in: ^5.4.1
  google_maps_flutter: ^2.1.12
  geolocator: ^9.0.1
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.5
  flutter_dotenv: ^5.0.2
  dot_navigation_bar: ^1.0.2
  flutter_vector_icons: ^1.0.0
  eva_icons_flutter: ^3.1.0
  material_dialogs: ^1.1.3
  cloud_firestore: ^4.8.4
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.3
  place_picker: ^0.9.19
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  firebase_storage: ^11.2.5
  flutter_screenutil: ^5.5.4
  carousel_slider: ^4.1.1
  page_transition: ^2.0.9
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/fonts/Work_Sans/
    - assets/fonts/
    - assets/
    - assets/imgs/
    - assets/svg/
    - assets/icons/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf