// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4MOlPYsS4RBkyl513Gms4OIORm8Mr8w',
    appId: '1:131955597136:web:36794e5681966252cf5655',
    messagingSenderId: '131955597136',
    projectId: 'khkys22',
    authDomain: 'khkys22.firebaseapp.com',
    storageBucket: 'khkys22.appspot.com',
    measurementId: 'G-XH5L3KHHKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABAbmMPTL-gQXsEsii2sioUTQfE8zJZVc',
    appId: '1:131955597136:android:5351ee21e16978dbcf5655',
    messagingSenderId: '131955597136',
    projectId: 'khkys22',
    storageBucket: 'khkys22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEK1VXeIKAZ0SFco-fH930UQ8Y2w7GVk',
    appId: '1:131955597136:ios:a7c95e80e248938ccf5655',
    messagingSenderId: '131955597136',
    projectId: 'khkys22',
    storageBucket: 'khkys22.appspot.com',
    androidClientId: '131955597136-mio3vmv54aoaq8bimvevnf7lgq0g8kpr.apps.googleusercontent.com',
    iosClientId: '131955597136-614egvtbe3pm39p2e960eurim1q7dgh3.apps.googleusercontent.com',
    iosBundleId: 'lorem.ipsum.traffix.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqEK1VXeIKAZ0SFco-fH930UQ8Y2w7GVk',
    appId: '1:131955597136:ios:a7c95e80e248938ccf5655',
    messagingSenderId: '131955597136',
    projectId: 'khkys22',
    storageBucket: 'khkys22.appspot.com',
    androidClientId: '131955597136-mio3vmv54aoaq8bimvevnf7lgq0g8kpr.apps.googleusercontent.com',
    iosClientId: '131955597136-614egvtbe3pm39p2e960eurim1q7dgh3.apps.googleusercontent.com',
    iosBundleId: 'lorem.ipsum.traffix.mobile',
  );
}
